[package]
name = "donutex"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29", default-features = false, features = ["glow", "default_fonts", "persistence"] }
egui = "0.29"
ropey = "1.6"
mlua = { version = "0.9", features = ["lua54", "vendored"] }
rfd = "0.15"
arboard = "3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
lsp-types = "0.97.0"
portable-pty = "0.9.0"
vt100 = "0.16.2"
anyhow = "1.0.104"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
